apiVersion: apps/v1
kind: Deployment
metadata:
  name: devprotool
  labels:
    app: devprotool
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devprotool
  template:
    metadata:
      labels:
        app: devprotool
    spec:
      containers:
        - name: devprotool
          image: 528757786303.dkr.ecr.ap-southeast-1.amazonaws.com/devprotool/devpro:latest
          ports:
            - containerPort: 80